# Deploy de produção para Firebase Hosting
name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create Firebase service account file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PLANNE_692F7 }}' > $HOME/firebase-service-account.json

      - name: Deploy to Firebase Hosting
        run: npx firebase-tools@15.22.3 deploy --only hosting --project planne-692f7
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-service-account.json